<?php

use Drupal\import_publication\PublicationParser\PublicationParser;

function import_publication_install() {
  
  	\Drupal\Core\Database\Database::setActiveConnection();
	$connection = \Drupal\Core\Database\Database::getConnection();

	$results = $connection->query('select bundle, entity_id, revision_id, langcode, delta, field_publications_value from node__field_publications;')->fetchAll();

	$logger = \Drupal::logger('import_publication');
	//$logger->notice(t("Query Results:" . print_r($results, true)));

	if ($results) {    
		foreach ($results as $record) {

			$year = PublicationParser::getYear($record->field_publications_value);
			$title = PublicationParser::getTitle($record->field_publications_value);
			$periodical = PublicationParser::getPeriodical($record->field_publications_value);
			$authors = PublicationParser::getAuthors($record->field_publications_value);


			$publication = entity_create('field_collection_item', array(
				"host_type" => "node",
				"field_name" => "field_collection_publication",
			));

			$logger->notice(t("Publication entity created. Used for Node ID ") . $record->entity_id);
			

			$current_node = \Drupal\node\Entity\Node::load($record->entity_id);
			$publication->setHostEntity($current_node);

			//$logger->notice(t("Host Entity Set."));
			
			$publication->field_publication_authors->value = $authors;
			$publication->field_article_title->value = $title;
			$publication->field_periodical_title->value = $periodical;
			$publication->field_publication_date->value = $year;
			$publication->field_publication_location->value ='publication location data';
			
			$logger->notice(t("Publication Fields set."));
			
			//save the field collection entity to the db
			$publication->save(TRUE);
			$logger->notice(t("New Entity of Publication <pre>" . print_r($publication->toArray(), true) . "</pre>"));
			
			$logger->notice(t("Publication id: " . print_r($publication->id(), true) ));
	
						
			//TODO: update to it doesnt override the first one each time.
			$current_node->field_collection_publication =  array( array( 'target_id' => $publication->id() ));

			$logger->notice(t("Node to add publication to:<pre> " . print_r($current_node->toArray(), true)  . "</pre>"));
			
			//Now save the node
			$current_node->save();
			
			break;
		}  

	}
	$logger->notice(t("Updated " . count($results) . " Publications."));
}